### ISSUE TITLE
AD410 Control of Deterrent Light

### ISSUE THREAD

**Issue by HeedfulCrayon** [rroller/dahua#116]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
I would like to be able to control the state of the deterrent light on the AD410 in home assistant

**Describe alternatives you've considered**
I have considered making the webrequest myself to control it
Turn On
> http://<cam_ip>/cgi cgi-bin/configManager.cgi?action=setConfig&Lighting_V2[0][0][1].Mode=ForceOn&Lighting_V2[0][0][1].State=On

Turn Off
> http://<cam_ip>/cgi cgi-bin/configManager.cgi?action=setConfig&Lighting_V2[0][0][1].Mode=Off

Turn On Strobe
> http://<cam_ip>/cgi cgi-bin/configManager.cgi?action=setConfig&Lighting_V2[0][0][1].Mode=ForceOn&Lighting_V2[0][0][1].State=Flicker

Adjust Brightness
> http://<cam_ip>/cgi cgi-bin/configManager.cgi?action=setConfig&Lighting_V2[0][0][1].MiddleLight[0].Light=<brightness level 0-100>

Get Brightness
> http://<cam_ip>/cgi cgi-bin/configManager.cgi?action=getConfig&Lighting_V2[0][0][1].MiddleLight[0].Light

**Comment by rroller** [comment]
I bought an AD410 so I can work on getting this soon. I'll have some free time in the next few weeks and will try to knock this out.

**Comment by GaryOkie** [comment]
Hey Ronnie - sure good to hear that you're getting an AD410.   It's working quite well with your integration as-is (using events).   There are some fine tuning needed for the sensors as you have already heard.     

There is also a new "stateless" Button integration in the beta HASS (2021.12-b) that would be a slightly better fit for the doorbell button than a binary sensor.   Once it is out, we can look at that as an enhancement request if it makes sense.

Oh, and about this little light that shines downward from the doorbell being called a "deterrent light" by Amcrest -  HA, that's funny. 

BTW - the Amcrest SmartHome app already has the option to turn on the light or make it strobe if motion or human is detected.    I'm not sure how useful adding all these services would be - especially for "deterrence".    And since the light is already quite dim, determining its brightness and adjusting it through HASS is quite the edge case.

@HeedfulCrayon - how do you see these HASS services being used effectively to control such a weak light?    If it were a flood light - that's a different story.

**Comment by HeedfulCrayon** [comment]
@GaryOkie I would prefer not to have the amcrest smart home app on my phone as it is a useless app IMO.  The reason why I want to control the light is because my porch doesn't have a whole lot of lighting as is, and this would help deter someone from possibly trying to steal the doorbell.  Plus the human detection turning on the light is all day.  I only want to have this happen specifically during the wee hours of the morning (after I have gone to bed)

**Comment by GaryOkie** [comment]
@HeedfulCrayon - I agree that being able to change the button ring color would be a  useful feature, but I sure don't think it was enabled in the AD410.     ​I have read that the very similar Lorex/Dahua 2K doorbell has this feature though.

I certainly understand wanting to avoid use of the SH app.   I do as well - except for the few times I need to answer the door remotely.  It's essential then.   You also can't avoid using the app to set up the darn thing.    

Everyone has different needs, so my apologies for questioning your enhancement request to control the light.   What I was really questioning is do we really need 5 more services developed?

In any case, it's up to RRoller to decide.

**Comment by rroller** [comment]
The security light feature is released in https://github.com/rroller/dahua/releases/tag/0.9.28
Please give it a try and let me know, thanks!

**Comment by rroller** [comment]
Resolving this issue now that the security light is now supported with this integration. Thanks for the idea! Please reopen if you have any issues.
