### ISSUE TITLE
View the thermal images

### ISSUE THREAD

**Issue by khara02** [rroller/dahua#162]
Hi,
Is there any way to view the thermal images that has on the model such as DH-TPC-BF3221T on hass dashboard?
https://dahuawiki.com/USA/IPCamera/PTZ/Thermal/DH-TPC-BF3221-T

**Comment by rroller** [comment]
I'm sure it's possible but I don't have a thermal cam to test with so I'm not sure how I'd build support for it. Maybe someone with one of these cams can help out.

**Comment by khara02** [comment]
Thank you for your reply,
Would you build support if I give you access to my camera?

**Comment by mooton85** [comment]
You shouldn't have a problem with this as the protocol is the same. Just note that as the camera is dual sensor each stream is a different channel, so add it twice once with channel "0" and once with channel "1".

If it does not work for you I can test it.

**Comment by khara02** [comment]
> You shouldn't have a problem with this as the protocol is the same. Just note that as the camera is dual sensor each stream is a different channel, so add it twice once with channel "0" and once with channel "1".
> 
> If it does not work for you I can test it.

Thank you for your reply.
I found rtsp address
rtsp://[id]:[pass]@[ip]:[port]/cam/realmonitor?channel=1&subtype=1
Then I changed 'channel=1' to 'channel=0' and some different numbers but the live image doesn't change.
I aslo tried changing the number of 'subtype=' but no luck.

**Comment by mooton85** [comment]
Changing the channel in the rtsp syntax may be "1" or "2" rather than a "0", I was referring to the connection details for the integration. 

Channel "0" = 2MP standard channel
Channel "1" = Thermal channel

You really shouldn't need to worry about the rtsp syntax at all as this isn't how it is added. Have you installed Rroller's integration fully?

I've just tested a BF2221-T (practically same model as yours) and it worked ok.

My configuration is as follows.....

If you've changed the http port or rtsp port on the camera then you need to reflect that here. Also if you are streaming from an NVR and not the cameras direct then you need to add the NVR connection details and then the relevant channels numbers with an offset of -1 (Channel 1 = 0, Channel 2 = 1 etc)

<img width="202" alt="thermal add" src="https://user-images.githubusercontent.com/63017818/154740829-0a5e651b-d196-4886-aff5-2ab289dc7a00.png">

Camera encode - make sure it's set to H.264 and make sure  to configure both channels (top left). If you don't want to affect your mainstream recording then I'd probably just use the sub and leave the main on H.265.

<img width="782" alt="thermal encode" src="https://user-images.githubusercontent.com/63017818/154742474-8693f8d5-a9c8-4e38-b30f-c5ea69b68c61.png">

With the above settings both channels stream fine......

<img width="1189" alt="thermal live" src="https://user-images.githubusercontent.com/63017818/154743033-bf860dd4-2634-498c-9d5a-a7007aa5b8a4.png">


If that still doesn't work for you please just provide some info on what you have tried and are getting exactly.

**Comment by khara02** [comment]
> Changing the channel in the rtsp syntax may be "1" or "2" rather than a "0", I was referring to the connection details for the integration.
> 
> Channel "0" = 2MP standard channel Channel "1" = Thermal channel
> 
> You really shouldn't need to worry about the rtsp syntax at all as this isn't how it is added. Have you installed Rroller's integration fully?
> 
> I've just tested a BF2221-T (practically same model as yours) and it worked ok.
> 
> My configuration is as follows.....
> 
> If you've changed the http port or rtsp port on the camera then you need to reflect that here. Also if you are streaming from an NVR and not the cameras direct then you need to add the NVR connection details and then the relevant channels numbers with an offset of -1 (Channel 1 = 0, Channel 2 = 1 etc)
> 
> <img alt="thermal add" width="202" src="https://user-images.githubusercontent.com/63017818/154740829-0a5e651b-d196-4886-aff5-2ab289dc7a00.png">
> 
> Camera encode - make sure it's set to H.264 and make sure to configure both channels (top left). If you don't want to affect your mainstream recording then I'd probably just use the sub and leave the main on H.265.
> 
> <img alt="thermal encode" width="782" src="https://user-images.githubusercontent.com/63017818/154742474-8693f8d5-a9c8-4e38-b30f-c5ea69b68c61.png">
> 
> With the above settings both channels stream fine......
> 
> <img alt="thermal live" width="1189" src="https://user-images.githubusercontent.com/63017818/154743033-bf860dd4-2634-498c-9d5a-a7007aa5b8a4.png">
> 
> If that still doesn't work for you please just provide some info on what you have tried and are getting exactly.

**Comment by khara02** [comment]
Thank you for your reply,
I uninstalled dahua integration from HAC which has installed by HACS install once, the I install in manual way to see if there be any changes but no luck.

During the process,
![01](https://user-images.githubusercontent.com/55570523/154785392-fc597ab7-c938-48f2-acc9-cb30c723cbaa.jpg)

I reffer your settings and I found there are couple options that I could check so I checked them all.
![02](https://user-images.githubusercontent.com/55570523/154785457-fa4fdf4c-a0b8-48d6-bf9d-e94a31c09a00.jpg)

Then I got 3 camera view just as before,
![03](https://user-images.githubusercontent.com/55570523/154785513-cf7b0636-2195-401f-b239-182621833cbb.jpg)

And the result of those 3 camera views on hass including rtsp image
![04](https://user-images.githubusercontent.com/55570523/154785527-26c5a14d-09a9-4277-b262-487fa9a2b963.jpg)
The main stream and sub stream just show same images but different resolutions.

This is how I see from Internet Explorer
![05](https://user-images.githubusercontent.com/55570523/154785535-4caf55ea-6d06-42b6-a1a8-c0131cfef64d.jpg)
I can see Thermal image in there.

I also reffered your setting on dahua
![07](https://user-images.githubusercontent.com/55570523/154785584-85cf8051-1f44-4fe5-8574-8fd4b8745003.jpg)

Sorry for that  the language on the images are dispalyed in Japanese.

**Comment by mooton85** [comment]
The main stream, sub stream & sub stream 2 are just different quality streams as you have noted. Each one is pulled from the same camera image/source but you have two "channels" to choose from. So you have six streams in total that you can customise the quality of on that camera (2x channels, 3x streams per channel).

Are you only adding the integration once? You need to add it twice. When you add the integration it will be the same exact settings (IP, user/pass etc) with the exception of the channel number at the bottom. The first time you add it put channel "0" which will give you the standard 2MP image.  Once that is all on and working go and add the integration again but this time put channel "1".

This should give you both channels with a Main, Sub & Sub 2 for each.

**Comment by khara02** [comment]
I see what you meant.

I added another integration as I followed your instruction.
![08](https://user-images.githubusercontent.com/55570523/154823289-b23edb0e-73a2-4309-8093-3489b9d3a11f.jpg)

And I finally got the thermal image from the camera!
![09](https://user-images.githubusercontent.com/55570523/154823308-c20aa613-ed30-4ce7-abdb-60a39397ed37.jpg)

But some how, I get this "Error with media stream contents (bufferAppendError)" when I try to enlarge the image by tapping the thermal cam card.
![10](https://user-images.githubusercontent.com/55570523/154823357-b5658437-b2f8-437f-a999-fb8369952593.jpg)

The standard 2MP image works fine.
