### ISSUE TITLE
Relationship with the internal `amcrest` integration

### ISSUE THREAD

**Issue by FrnchFrgg** [rroller/dahua#41]
Home Assistant ships with an `amcrest` integration, which supports through `pyamcrest` a lot of Dahua products too. This raises several questions:
* What advantages does the integration here have over that `amcrest` integration ?
* Would it be possible to improve the `amcrest` integration and/or `pyamcrest` instead of writing a completely new one, or
* Would it be possible to get inspiration from that `amcrest` integration and check for parts of the Dahua API that are better supported by `pyamcrest` ?
* Maybe the path forward is to write an equivalent to `pyamcrest` with the code here if it is better, then modify the internal `amcrest` integration to use that new code ?
* Or if you think that your integration should stay separate, explain why in the README so that users can decide whether the internal `amcrest` or yours is better. Then maybe try to merge your integration into Home Assistant itself.

**Comment by rroller** [comment]
* advantages:  This dahua integration supports more features, it is actively maintained, and it is outside the release cycle of HA so it can have multiple updates per day/week or however often new features
* I don't want to improve the amcrest one because it's branded as amcrest and not dahua. For now I want to keep this seperate so I can have quick updates outside of the HA development process which has pretty rigorous reviews and slow turn around times
* I can look at pyamcrest. Wasn't aware of it  until now
* I like the idea of creating a new lib from the API client I'm writing (which I plan to rewrite to improve the quality of). I can look at making that a library
* I do plan on trying to add this Dahua integration directly to HA once I mature it and it becomes nearly feature complete and all bugs are worked out. Doing so now would really slow dev time. But that's the plan. Updated the readme - https://github.com/rroller/dahua/commit/c28a01390d2f7c98c044d714e74974c1cebadb60
