### ISSUE TITLE
Missing binary sensor - button pressed

### ISSUE THREAD

**Issue by djxela** [rroller/dahua#61]
I have VTO 2211G-P everything works good but I dont see binary sensor which reports when butt is pressed.  In configuration I have checked  option "binary sensor". Do you know what is the problem?

**Comment by rroller** [comment]
It should look like this...

![image](https://user-images.githubusercontent.com/445655/126875781-2df7a43e-64e7-40a5-8ca5-f807d3055ca7.png)

**Comment by djxela** [comment]
I have only these:
![46F9075A-E8B9-4762-ACD5-8E16E9A4E9B1](https://user-images.githubusercontent.com/36244426/126877819-e7f83f92-120e-415e-bb6b-4db8fa4e8ea3.jpeg)

**Comment by djxela** [comment]
Also after upgrade I dont have new entity: switch to  open the door

**Comment by djxela** [comment]
Should it appear automatically after configuration finisz or I should configure it manually?

**Comment by djxela** [comment]
This from dahuavto2mqtt works:
![909504FC-C92A-4BD6-A2AC-31292E01ECB6](https://user-images.githubusercontent.com/36244426/126879071-90ca4ee2-18c2-4d92-8746-20ee98c4137c.jpeg)

**Comment by rroller** [comment]
It should just show up

**Comment by djxela** [comment]
So what could be the problem

**Comment by papinist** [comment]
I have the same problem - missing binary sensor about button press. I have a VTO3211D-P4-S2.
Btw your integration works perfect with this VTO :)

**Comment by nibblerrick** [comment]
I have a VTO3211D, too, but the P2. The binary sensor is there, so that's not a problem. But is has two buttons, so I agree, it would be nice to have two sensors, one for each button. Otherwise the integrations works fine with the VTO3211D-P2 and a VTO2202F!

**Comment by papinist** [comment]
Ok I found the binary sensor - I was confused that it does not appear in the device's entity list, but when creating an automation, it is present.
However it would be useful to have distinct sensors for each button.
Thanks!

**Comment by rroller** [comment]
@papinist @nibblerrick  you can always use the event bus instead of the binary sensors. See https://github.com/rroller/dahua/blob/main/README.md#events

All button presses, etc are fired on the HA event bus and you can create automations from that. The binary sensors are just kind of nice-to-have helpers for simpler cases.

For adding the other buttons... can enable debug logging, press the other button, and paste the event data here? I don't have a unit with two or more buttons so I'll need the event data to try and add it.
